### ISSUE TITLE
Welcome to PancakeSwap Sniper bot! Missing or wrong tokenAddress parameter.

### ISSUE THREAD

**Issue by Peaceislove1996** [mnedelchev-vn/pancakeswap-sniper-bot#3] opened 2021-07-21 12:02 UTC
can you please tell me where i can put my api key and token to purchase adress and the amount that i want to buy, i cannot find it inside the code . thanks

**Comment by mnedelchev-vn** [comment] 2021-08-07 09:57
This issue has been answered already and is duplicate of #4

**Closed by mnedelchev-vn** 2021-08-07 09:57 UTC
